apiVersion: apps/v1
kind: Deployment
metadata:
  name: anyway-backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: anyway-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: anyway-backend
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    spec:
      containers:
        image: eu.gcr.io/anyway-backend/anyway-backend
        imagePullPolicy: IfNotPresent
        name: anyway-backend
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

