apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "anyway-backend"
  namespace: "default"
  labels:
    app: "anyway-backend"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 15
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: "anyway-backend"
  template:
    metadata:
      labels:
        app: "anyway-backend"
    spec:
      containers:
      - name: "anyway-backend"
        image: "eu.gcr.io/anyway-backend/anyway-backend"
      restartPolicy: Always



---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "anyway-backend-service"
  namespace: "default"
  labels:
    app: "anyway-backend"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  selector:
    app: "anyway-backend"
  type: "LoadBalancer"
